<h2><?= $this->translate('Plugin Output') ?></h2>
<div class="collapsible-container" data-height="52">
    <div class="collapsible"><?= $this->pluginOutput($object->output, false, $object->check_command) ?></div>
</div>
<!--Dummy Collapsible Containers-->
<h3>This Container's collapsible-id is not unique</h3>
<div class="collapsible-container" data-height="36" data-collapsible-id="<?= $object->getName() ?>1">
    <div class="collapsible">Sed posuere consectetur est at lobortis. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Curabitur blandit tempus porttitor. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</div>
</div>
<h3>Output 2</h3>
<div class="collapsible-container" data-height="36" data-collapsible-id="<?= $object->getName() ?>2">
    <div class="collapsible">Sed posuere consectetur est at lobortis. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Curabitur blandit tempus porttitor. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</div>
</div>
<h3>Output 3</h3>
<div class="collapsible-container" data-height="36" data-collapsible-id="<?= $object->getName() ?>3">
    <div class="collapsible">Sed posuere consectetur est at lobortis. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Curabitur blandit tempus porttitor. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</div>
</div>
<h3>This Container's collapsible-id is not unique</h3>
<div class="collapsible-container" data-height="36" data-collapsible-id="<?= $object->getName() ?>1">
    <div class="collapsible">Sed posuere consectetur est at lobortis. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Curabitur blandit tempus porttitor. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</div>
</div>
<h3>This Container has no collapsible id</h3>
<div class="collapsible-container" data-height="36">
    <div class="collapsible">Sed posuere consectetur est at lobortis. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Curabitur blandit tempus porttitor. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</div>
</div>
<!-- END Dummy Collapsible Containers-->
